### ISSUE TITLE
bottom not working

### ISSUE THREAD

**Issue by eugenevk** [emmanuelsw/notiwind#10] opened 2021-11-11 17:14 UTC
If I use the "bottom" option (copied straight the example), no message is displayed at all. Nothing happens in that case. The other examples work fine.
Am using VueJS 3 (Composition API) with TailwindCSS 2.2.17.

This is how the HTML of my App.vue looks:
```
<template>
  <NavBar v-if="authenticatedUser" />
  <div class="w-full">
    <TitleBar v-if="authenticatedUser" @logout="logoutUser" />
    <div class="flex flex-col">
      <NotificationGroup
        group="bottom"
        position="bottom"
      >
        <div class="fixed inset-x-0 bottom-0 flex items-start justify-end p-6 px-4 py-6 pointer-events-none">
          <div class="w-full max-w-sm">
            <Notification
              v-slot="{ notifications }"
              enter="transform ease-out duration-300 transition"
              enter-from="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-4"
              enter-to="translate-y-0 opacity-100 sm:translate-x-0"
              leave="transition ease-in duration-500"
              leave-from="opacity-100"
              leave-to="opacity-0"
              move="transition duration-500"
              move-delay="delay-300"
            >
              <div
                v-for="notification in notifications"
                :key="notification.id"
                class="flex w-full max-w-sm mx-auto mt-4 overflow-hidden bg-white rounded-lg shadow-md"
              >
                <div class="flex items-center justify-center w-12 bg-red-500">
                  <svg
                    class="w-6 h-6 text-white fill-current"
                    viewBox="0 0 40 40"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"
                    />
                  </svg>
                </div>

                <div class="px-4 py-2 -mx-3">
                  <div class="mx-3">
                    <span class="font-semibold text-red-500">{{ notification.title }}</span>
                    <p class="text-sm text-gray-600">
                      {{ notification.text }}
                    </p>
                  </div>
                </div>
              </div>
            </Notification>
          </div>
        </div>
      </NotificationGroup>

      <NotificationGroup group="success" position="bottom">
        <div class="fixed inset-x-0 bottom-0 flex items-start justify-end p-6 px-4 py-6 pointer-events-none">
          <div class="w-full max-w-sm">
            <Notification
              v-slot="{ notifications }"
              enter="transform ease-out duration-300 transition"
              enter-from="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-4"
              enter-to="translate-y-0 opacity-100 sm:translate-x-0"
              leave="transition ease-in duration-500"
              leave-from="opacity-100"
              leave-to="opacity-0"
              move="transition duration-500"
              move-delay="delay-300"
            >
              <div
                class="flex w-full max-w-sm mx-auto mt-4 overflow-hidden bg-white rounded-lg shadow-md"
                v-for="notification in notifications"
                :key="notification.id"
              >
                <div class="flex items-center justify-center w-12 bg-primary-green-900">
                  <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                    <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z" />
                  </svg>
                </div>

                <div class="px-4 py-2 -mx-3">
                  <div class="mx-3">
                    <span class="font-semibold text-primary-green-900">{{ notification.title }}</span>
                    <p class="text-sm text-gray-600">{{ notification.text }}</p>
                  </div>
                </div>
              </div>
            </Notification>
          </div>
        </div>
      </NotificationGroup>

      <NotificationGroup group="error">
        <div class="fixed inset-0 flex items-start justify-end p-6 px-4 py-6 pointer-events-none">
          <div class="w-full max-w-sm">
            <Notification
              v-slot="{ notifications }"
              enter="transform ease-out duration-300 transition"
              enter-from="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-4"
              enter-to="translate-y-0 opacity-100 sm:translate-x-0"
              leave="transition ease-in duration-500"
              leave-from="opacity-100"
              leave-to="opacity-0"
              move="transition duration-500"
              move-delay="delay-300"
            >
              <div
                class="flex w-full max-w-sm mx-auto mt-4 overflow-hidden bg-white rounded-lg shadow-md"
                v-for="notification in notifications"
                :key="notification.id"
              >
              <div class="flex items-center justify-center w-12 bg-primary-red-900">
                <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                  <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"/>
                </svg>
              </div>

              <div class="px-4 py-2 -mx-3">
                <div class="mx-3">
                  <span class="font-semibold text-primary-red-900">{{ notification.title }}</span>
                  <p class="text-sm text-gray-600">{{ notification.text }}</p>
                </div>
              </div>
              </div>
            </Notification>
          </div>
        </div>
      </NotificationGroup>

      <NotificationGroup group="info">
        <div class="fixed inset-0 flex items-start justify-end p-6 px-4 py-6 pointer-events-none">
          <div class="w-full max-w-sm">
            <Notification
              v-slot="{ notifications }"
              enter="transform ease-out duration-300 transition"
              enter-from="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-4"
              enter-to="translate-y-0 opacity-100 sm:translate-x-0"
              leave="transition ease-in duration-500"
              leave-from="opacity-100"
              leave-to="opacity-0"
              move="transition duration-500"
              move-delay="delay-300"
            >
              <div
                class="flex w-full max-w-sm mx-auto mt-4 overflow-hidden bg-white rounded-lg shadow-md"
                v-for="notification in notifications"
                :key="notification.id"
              >
                <div class="flex items-center justify-center w-12 bg-secondary-blue-900">
                  <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                    <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM21.6667 28.3333H18.3334V25H21.6667V28.3333ZM21.6667 21.6666H18.3334V11.6666H21.6667V21.6666Z"/>
                  </svg>
                </div>

                <div class="px-4 py-2 -mx-3">
                  <div class="mx-3">
                    <span class="font-semibold text-secondary-blue-900">{{ notification.title }}</span>
                    <p class="text-sm text-gray-600">{{ notification.text }}</p>
                  </div>
                </div>
              </div>
            </Notification>
          </div>
        </div>
      </NotificationGroup>

      <router-view @authenticated="setAuthenticatedUser" />
    </div>
  </div>
</template>
...
```

**Comment by emmanuelsw** [comment] 2021-11-16 16:28
Hello, can you provide a reproduction repo? Because I tested both your code and the example and they are working correctly.

**Comment by cheyanru** [comment] 2021-12-22 18:04
Hi @emmanuelsw I believe what @eugenevk want is to align the notification at the bottom right corner of the page, but what the `position="bottom"` does is appending the notifications at the end of the list, instead of inserting from the top, it does not change the alignment of the notifications, which is top right corner. 

@eugenevk actually you can do that by changing the `items-start` class to `items-end`, this will align all your notifications to the bottom right corner. example code below: 

instead of this

`<NotificationGroup
        group="bottom"
        position="bottom"
      >
        <div class="fixed inset-x-0 bottom-0 flex items-start justify-end p-6 px-4 py-6 pointer-events-none">`

do this  
      
`<NotificationGroup
        group="bottom"
        position="bottom"
      >
        <div class="fixed inset-x-0 bottom-0 flex **items-end** justify-end p-6 px-4 py-6 pointer-events-none">`

**Comment by emmanuelsw** [comment] 2021-12-23 18:02
@cheyanru thank you for the detailed reply!
That's exactly how it works, and that's why it's headless.

I'm closing this for now.

**Closed by emmanuelsw** 2021-12-23 18:02 UTC

**Comment by eugenevk** [comment] 2021-12-25 08:16
Hi @cheyanru and @emmanuelsw, even when I change items-start to items-end, the notification still shows at the top right corner. Any other suggestion?

**Comment by eugenevk** [comment] 2021-12-25 08:25
Yes, this solves it. Great, thank you @cheyanru !
